/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.CarDirectory;
import Business.Car;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JAINHEMANT
 */
public class CreateCarJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateCarJPanel
     */
    private CarDirectory carDirectory;
    private JPanel rightPanel;
    private int error;

    ButtonGroup BTNgrup;

    public CreateCarJPanel(JPanel rightPanel, CarDirectory carDirectory) {
        initComponents();
        this.carDirectory = carDirectory;
        this.rightPanel = rightPanel;

        unavailableRadiobtn.setSelected(true);

        //Group the Radio Buttons
        BTNgrup = new ButtonGroup();
        BTNgrup.add(availableRadiobtn);
        BTNgrup.add(unavailableRadiobtn);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        modelNametxt = new javax.swing.JTextField();
        modelNotxt = new javax.swing.JTextField();
        availableCitytxt = new javax.swing.JTextField();
        minimumSeattxt = new javax.swing.JTextField();
        manufacturertxt = new javax.swing.JTextField();
        manufacturerYeartxt = new javax.swing.JTextField();
        serialNotxt = new javax.swing.JTextField();
        maximumSeattxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        maintainenceCerttxt = new javax.swing.JTextField();
        availableRadiobtn = new javax.swing.JRadioButton();
        unavailableRadiobtn = new javax.swing.JRadioButton();
        addCarbtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("UBER ADD NEW CARS");

        jLabel2.setText("ModelName");

        jLabel3.setText("ModelNo");

        jLabel4.setText("AvailableCity");

        jLabel5.setText("Minimum Seat");

        jLabel6.setText("Manufacturer");

        jLabel7.setText("Manufacturer Year");

        jLabel8.setText("SerialNo");

        jLabel9.setText("Maximum Seat");

        modelNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelNametxtActionPerformed(evt);
            }
        });

        manufacturertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturertxtActionPerformed(evt);
            }
        });

        manufacturerYeartxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturerYeartxtActionPerformed(evt);
            }
        });

        serialNotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNotxtActionPerformed(evt);
            }
        });

        maximumSeattxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maximumSeattxtActionPerformed(evt);
            }
        });

        jLabel10.setText("Maintainence Certificate Expiry Date");

        availableRadiobtn.setText("Available");

        unavailableRadiobtn.setText("Unavailable");

        addCarbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addCarbtn.setText("ADD CAR");
        addCarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCarbtnActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBack.setText("<<BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maintainenceCerttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel2))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(modelNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(103, 103, 103)
                                                .addComponent(jLabel6))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(modelNotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(103, 103, 103)
                                                .addComponent(jLabel7))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(availableCitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(minimumSeattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(103, 103, 103)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel8))))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(manufacturerYeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(manufacturertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(serialNotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(maximumSeattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(availableRadiobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unavailableRadiobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addComponent(addCarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(modelNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(modelNotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manufacturerYeartxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(availableCitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(minimumSeattxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(maximumSeattxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maintainenceCerttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addCarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(availableRadiobtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unavailableRadiobtn))
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manufacturertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturertxtActionPerformed

    private void manufacturerYeartxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturerYeartxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manufacturerYeartxtActionPerformed

    private void serialNotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNotxtActionPerformed

    private void maximumSeattxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maximumSeattxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maximumSeattxtActionPerformed

    private void modelNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelNametxtActionPerformed


    private void addCarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCarbtnActionPerformed
        // TODO add your handling code here:

        error = 0;
        String modelName = modelNametxt.getText();
        String modelNo = modelNotxt.getText();
        String manufac = manufacturertxt.getText();
        String manufacYr = manufacturerYeartxt.getText();
        String availCity = availableCitytxt.getText();
        String maintainCert = maintainenceCerttxt.getText();
        String serNo = serialNotxt.getText();
        String maxSeat = maximumSeattxt.getText();
        String minSeat = minimumSeattxt.getText();
        Boolean avail;

        if (BTNgrup.getSelection() == availableRadiobtn.getModel()) {
            avail = true;

        } else {
            avail = false;
        }

        //Validation code for each text field are added here:
        checkInteger(modelNo, "Model Number");
        checkString(modelName, "Model Name");
        checkString(manufac, "Manufacturer");
        checkDate(manufacYr,"Manufacturing Year");
        checkString(availCity, "Available City");
        checkDate(maintainCert,"Maintain Cert Expiry");
        checkInteger(serNo, "Serial Number");
        checkInteger(maxSeat, "Maximum Seat");
        checkInteger(minSeat, "Minimum Seat");

        //Continuation of the code
        if (Integer.parseInt(minSeat) > Integer.parseInt(maxSeat)) {
            error = 1;
            JOptionPane.showMessageDialog(null, "Maximum Seat Should be more than Minimum seat", "Error", 0);
        }

        if (error != 1) {
            //Code to add the new car details
            Car car = new Car();
            car.setModelName(modelName);
            car.setModelNo(modelNo);
            car.setManufacturer(manufac);
            car.setMaintainCert(maintainCert);
            car.setManufactureyear(manufacYr);
            car.setMaxSeat(Integer.parseInt(maxSeat));
            car.setMinSeat(Integer.parseInt(minSeat));
            car.setAvailability(avail);
            car.setAvailableCity(availCity);
            car.setSerialNo(serNo);

            carDirectory.addCarList(car);
            JOptionPane.showMessageDialog(null, "Car Details added Successfully");

            modelNametxt.setText("");
            modelNotxt.setText("");
            manufacturertxt.setText("");
            manufacturerYeartxt.setText("");
            maintainenceCerttxt.setText("");
            availableCitytxt.setText("");
            maximumSeattxt.setText("");
            minimumSeattxt.setText("");
            serialNotxt.setText("");
    }//GEN-LAST:event_addCarbtnActionPerformed
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.rightPanel.remove(this);
        CardLayout layout = (CardLayout) this.rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCarbtn;
    private javax.swing.JTextField availableCitytxt;
    private javax.swing.JRadioButton availableRadiobtn;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maintainenceCerttxt;
    private javax.swing.JTextField manufacturerYeartxt;
    private javax.swing.JTextField manufacturertxt;
    private javax.swing.JTextField maximumSeattxt;
    private javax.swing.JTextField minimumSeattxt;
    private javax.swing.JTextField modelNametxt;
    private javax.swing.JTextField modelNotxt;
    private javax.swing.JTextField serialNotxt;
    private javax.swing.JRadioButton unavailableRadiobtn;
    // End of variables declaration//GEN-END:variables

    //Integer values validations
    private void checkInteger(String checkThis, String fieldValue) {
        try {
            if (Double.parseDouble(checkThis) % 1 != 0) {
                error = 1;
                JOptionPane.showMessageDialog(null, fieldValue + " should not be in fraction", "ERROR", 0);
            }
        } catch (Exception e) {
            error = 1;
            JOptionPane.showMessageDialog(null, fieldValue + " should be in Number format", "ERR0R", 0);
        }
    }
    //String values validations function
    private void checkString(String checkThis, String fieldValue) {
        try {
            if (Double.valueOf(Double.parseDouble(checkThis)) >= 0) {
                error = 1;
                JOptionPane.showMessageDialog(null, "Please enter " + fieldValue + " in proper format", "Error", 0);
            }
        } catch (Exception e) {

        }
    }
    //Date field values validations function
    private void checkDate(String checkThis, String fieldValue) {
         try
        {
            if(Double.valueOf(Double.parseDouble(checkThis))>=0);
            {
                error=1;
                JOptionPane.showMessageDialog(null,"Please enter "+fieldValue +"Date in proper format", "Error", 0);
            }
        }
        catch(Exception e)
        {
                if(!getDateRegex(checkThis))
                {
                    error=1;
                    JOptionPane.showMessageDialog(null,"Please Enter "+fieldValue +"date in format MM-DD-YYYY","ERROR",0);
                }    
                    
                    
        }
    }
    
    private boolean getDateRegex(String date)
    {
        //String regex= "\\d{2}\\-\\d{2}\\-\\d{4}";
        String dRegex="^(0[0-9]|1[0-2])\\-(0[1-9]|1[0-9]|2[0-9]|3[0-1])\\-(199[0-9]|20[0-1][0-8])";
        final Pattern pattern = Pattern.compile(dRegex);
        boolean bool=pattern.matcher(date).matches();
        return bool;
            
    }

  

}
